apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: placeholder-minio-api-strip@kubernetescrd
spec:
  rules:
    - host: placeholder.domain-placeholder
      http:
        paths:
          - path: /buckets
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  name: http
