name: Build torus-builder Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    name: Build torus-builder Docker Image
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ”‘ Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SIMON_DOCKERHUB_USERNAME }}
          password: ${{ secrets.SIMON_DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

        # builds the torus-builder image, used to build the release for Amazon Linux 2
      - name: ğŸ³ Build and push torus-builder image
        uses: docker/build-push-action@v2
        with:
          context: ./.github/actions/torus-builder
          push: true
          tags: olisimon/torus-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
