name: Build torus-builder Docker Image

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: "Tag for the Docker image"

jobs:
  elixir-build-test:
    name: Elixir build and test
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

        # builds the torus-builder image, used to build the release for Amazon Linux 2
      - name: ğŸ³ Build and push torus-builder image
        uses: docker/build-push-action@v2
        with:
          context: ./.github/actions/torus-builder
          push: true
          tags: torus-builder:latest,torus-builder:${{ github.event.inputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
